version: '3'

services:
  db:
    image: postgres:15.4
    restart: always
    container_name: test-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test123



